# Generated by Django 3.2.6 on 2021-08-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pub_data_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questuion',
            new_name='questuion_text',
        ),
    ]
