# Generated by Django 3.2.6 on 2021-08-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_questuion_question_questuion_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questuion_text',
            new_name='question_text',
        ),
    ]
